### ISSUE TITLE
add public_key to Adyen create/update

### ISSUE THREAD

**Issue by korsvanloon** [incentro-dc/terraform-provider-commercelayer#90]
Even though you can provide a public_key for Adyen, it seems it is not used.

https://github.com/incentro-dc/terraform-provider-commercelayer/blob/main/commercelayer/resource_adyen_gateway.go#L166

**Comment by incentrotolgaakyazi** [comment]
@kors Hi Kors! We added `public_key` to the create/update for the Adyen gateway in the newest release (v0.0.12).
