### ISSUE TITLE
Add custom field resource for processing options -> Transaction -> <Custom field list>

### ISSUE THREAD

**Issue by tjad-oivan** [incentro-dc/terraform-provider-commercelayer#96]
Scroll up
https://sandbox.braintreegateway.com/merchants/<YOUR_MERCHANT_ID/processing#transactions

**Comment by demeyerthom** [comment]
Hi @tjad-oivan! Thanks for reaching out!

Mind adding a bit more information about what you are missing exactly? As far as I can tell we have all the fields in the configuration as specified by the API documentation: [https://docs.commercelayer.io/core/v/api-reference/braintree_gateways/create](https://docs.commercelayer.io/core/v/api-reference/braintree_gateways/create)

Am I missing anything here?

**Comment by tjad-oivan** [comment]
Hi @demeyerthom, 
Thank you for responding. Perhaps it is not part of the API yet :thinking: 
If this is the case, we would need to get braintree to add it as part of their API. 

I have looked at the API details briefly and did not spot a related item.

This is specifically for "Custom Fields" of a transaction which is configurable with the above link provided.

I will try to open a ticket to braintree regarding this and leave a link here. Hopefully we can make progress on this to have a feature complete API  - and accompanying library.

**Comment by demeyerthom** [comment]
Hi @tjad-oivan 
I would suggest contacting commercelayer about it first. They are the one actually implementing the API. It might be Braintree supports these fields, but Commercelayer does not.

Let me know once there is movement here! As soon as it is included in the Commercelayer API I will add it to the provider also!

**Comment by tjad-oivan** [comment]
Okay! Thanks, that is helpful to know - yes I'm new to Braintree :sweat_smile:

Will update here once make progress

**Comment by demeyerthom** [comment]
Happy to help :+1:

**Comment by jobveldhuis** [comment]
We're closing this, because of inactivity on the issue. If there is movement, feel free to reopen!
